### ISSUE TITLE
Suggestion: issue tracking + discussions enabled

### ISSUE THREAD

**Issue by ivanbelenky** [anl-rtr/adder#2]
Hey there, I was wondering if there is room for both

- creating gh issues 1to1 mapped to the ones posted [here](https://github.com/anl-rtr/adder/blob/main/List%20of%20known%20ADDER%20bugs.docx) and update them appropriately.
- enable discussions for this repo to expose plans for api new releases, and updates overall

**Comment by vmascolino-anl** [comment]
Hi!

Thanks for your comment. These are great suggestions, and we will look into implementing both after the release of ADDER v1.1.0 that will solve all the reported bugs. 

ADDER v1.1.0 should release before the end of the calendar year 2024.

Please don't hesitate to contact us either here or at adder@anl.gov should you need any additional support.

Valerio
